spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

api:
  key : 78VM16BGS9427RH1MGSE

kobis:
  boxoffice :
  key : 5431a979f391d9ef29ec3b0c5a397219

tmdb:
  key: 08637c4f198bed78701a8e1770d54f19


mail:
  address:
    admin: admin@gmail.com

jwt:
  key : ajdfakwje@qw4iekjr293k4kjd9x9d902kjldf0p2934
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420