spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

kmdb:
  key : {KMDB_KEY}

kobis:
  key : {KOBIS_KEY}

tmdb:
  key: {TMDB_KEY}


mail:
  address:
    admin: admin@gmail.com

jwt:
  key : {JWT_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

